# Generated by Django 3.2 on 2023-02-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230228_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.comment'),
        ),
    ]
